baseurl: "https://hornjourney.com/"
languageCode: "en-us"
title: "Horn Journey"

permalinks:
  post: "/post/:year/:month/:day/:slug/"

menu:
  main:
    - identifier: archive
      name: Archive
      url: "post/"
      weight: 1
    - identifier: follow
      name: Follow
      url: "follow/"
      weight: 2
    - identifier: neighborhood
      name: Neighborhood
      url: "neighborhood/"
      weight: 3
    - identifier: about
      name: About
      url: "about/"
      weight: 4
    - identifier: about-me
      name: "Me"
      url: "about/"
      parent: about
      weight: 1
    - identifier: now
      name: "Now"
      url: "now/"
      parent: about
      weight: 2
    - identifier: site
      name: "Site"
      url: "about-site/"
      parent: about
      weight: 3
    - identifier: contact
      name: "Contact"
      url: "contact/"
      parent: about
      weight: 4

# Last modified date in Hugo (https://mertbakir.gitlab.io/hugo/last-modified-date-in-hugo/)
frontmatter:
  date:
    - date
    - publishDate
    - lastmod
  lastmod:
    - lastmod
    - ':git'
    - date
    - publishDate
  publishDate:
    - publishDate
    - date
  expiryDate:
    - expiryDate


params:
  description: "Exploring paths for learning and musicianship on the French horn"
  author: "Steve Eddins"
  startYear: "2023"
  dateFormat: "Monday, January 2, 2006"
  siteLogo: "image/horn-logo.svg"
  ShowFullTextinRSS: true
  footerLinks:
    - github:
      name: "GitHub"
      url: "https://github.com/eddins"
    - mathworks:
      name: "MathWorks blog"
      url: "https://blogs.mathworks.com/steve"

markup:
  highlight:
    codeFences: false
  goldmark:
    renderer:
      unsafe: true
