baseurl: "/"
languageCode: "en-us"
title: "Horn Journey"
googleAnalytics: ""
disqusShortname: ""
ignoreFiles: ["\\.Rmd$", "\\.Rmarkdown$", "_cache$"]
footnotereturnlinkcontents: "↩"

permalinks:
  note: "/note/:year/:month/:day/:slug/"
  post: "/post/:year/:month/:day/:slug/"

menu:
  main:
    - name: Home
      url: ""
      weight: 1
    - name: Posts
      url: "post/"
      weight: 2
    - name: Follow
      url: "follow/"
      weight: 3
    - name: Neighborhood
      url: "neighborhood/"
      weight: 4
    - name: Now
      url: "now/"
      weight: 5
    - name: Contact
      url: "contact/"
      weight: 7

# Last modified date in Hugo (https://mertbakir.gitlab.io/hugo/last-modified-date-in-hugo/)
frontmatter:
  date:
    - date
    - publishDate
    - lastmod
  lastmod:
    - lastmod
    - ':git'
    - date
    - publishDate
  publishDate:
    - publishDate
    - date
  expiryDate:
    - expiryDate


params:
  description: "A website built through Hugo and blogdown."
  author: "Steve Eddins"
  startYear: "2023"
  dateFormat: "Monday, January 2, 2006"
  footerLinks:
    - github:
      name: "GitHub"
      url: "https://github.com/eddins"
    - mathworks:
      name: "MathWorks blog"
      url: "https://blogs.mathworks.com/steve"

markup:
  highlight:
    codeFences: false
  goldmark:
    renderer:
      unsafe: true
